#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "factorio_watch"

# Get arguments
args = ARGV
if args.length < 4
  puts "Usage: #{$PROGRAM_NAME} <factorio_path> <factorio_args>"
  return
end

factorio_path = args[0]
factorio_args = args[1..]
endpoint = ENV["DISCORD_WEBHOOK"]
if endpoint.nil?
  puts "DISCORD_WEBHOOK environment variable is not set"
  Kernel.exit(1)
end
FactorioWatch.watch_factorio(factorio_path, factorio_args, endpoint)
